import { AssetDetailItem } from "@/types";
import { Address } from "viem";

export const ASSET_ICONS: Record<string, string> = {
  tAAPL: "https://logo.clearbit.com/apple.com",
  tNVDA: "https://cdn-icons-png.flaticon.com/512/732/732230.png",
  tMSFT: "https://logo.clearbit.com/microsoft.com",
  tGOOGL: "https://logo.clearbit.com/google.com",
  tD05: "https://companieslogo.com/img/orig/D05.SI-edfcd000.png?t=1720244491",
  tBREN: "https://www.barito-pacific.com/fe/assets/icons/favicon_barito1.png",
  tDELTA: "https://www.deltathailand.com/imgadmins/news/news_cover/DELTA_news_photo2019-02-27_15-17-12.jpg",
  tMAYBANK: "https://w7.pngwing.com/pngs/280/197/png-transparent-maybank-finance-money-permodalan-nasional-berhad-interior-design-logo-saving-food-text.png",
  tXAU: "https://cdn-icons-png.flaticon.com/512/2583/2583963.png",
  tXAG: "https://cdn-icons-png.flaticon.com/512/2583/2583967.png",
  tBTC: "https://cdn-icons-png.flaticon.com/512/5968/5968260.png",
  tTSLA: "https://logo.clearbit.com/tesla.com",
  tETH: "https://cdn-icons-png.flaticon.com/512/14446/14446160.png",
  DEFAULT: "/icons/assets/default-asset.svg",
};

export const ASSET_DETAILS: Record<string, AssetDetailItem> = {
  tAAPL: {
    tokenAddress: "0xdf1a0e84ad813a178cdcf6fdfec1876f78bb471d" as Address,
    name: "Tokenized Apple Stock",
    symbol: "tAAPL",
    price: "$230.00",
    lastUpdated: new Date(),
    assetType: "STOCK",
    assetIcon: "https://logo.clearbit.com/apple.com",
    companyName: "Apple Inc.",
    marketCap: "$3.5T",
    website: "https://www.apple.com",
    industry: "Consumer Electronics",
    country: "United States",
    sharesOutstanding: "15.5B",
    description:
      "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.",
    foundedYear: 1976,
    latestNews: [],
  },
  tNVDA: {
    tokenAddress: "0x0000000000000000000000000000000000000000" as Address,
    name: "Tokenized NVIDIA Stock",
    symbol: "tNVDA",
    price: "$450.00",
    lastUpdated: new Date(),
    assetType: "STOCK",
    assetIcon: "https://cdn-icons-png.flaticon.com/512/732/732230.png",
    companyName: "NVIDIA Corporation",
    marketCap: "$1.8T",
    website: "https://www.nvidia.com",
    industry: "Semiconductors",
    country: "United States",
    sharesOutstanding: "2.5B",
    description:
      "NVIDIA Corporation operates as a visual computing company specializing in graphics processing units and AI computing.",
    foundedYear: 1993,
    latestNews: [],
  },
  tMSFT: {
    tokenAddress: "0x7a346368cb82bca986e16d91fa1846f3e2f2f081" as Address,
    name: "Tokenized Microsoft Stock",
    symbol: "tMSFT",
    price: "$415.00",
    lastUpdated: new Date(),
    assetType: "STOCK",
    assetIcon: "https://logo.clearbit.com/microsoft.com",
    companyName: "Microsoft Corp.",
    marketCap: "$3.1T",
    website: "https://www.microsoft.com",
    industry: "Software",
    country: "United States",
    sharesOutstanding: "7.4B",
    description:
      "Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide.",
    foundedYear: 1975,
    latestNews: [],
  },
  tGOOG: {
    tokenAddress: "0x067556d409d112376a5c68cde223fdae3a4bd62b" as Address,
    name: "Tokenized Alphabet Stock",
    symbol: "tGOOG",
    price: "$175.00",
    lastUpdated: new Date(),
    assetType: "STOCK",
    assetIcon: "https://logo.clearbit.com/google.com",
    companyName: "Alphabet Inc.",
    marketCap: "$2.1T",
    website: "https://www.google.com",
    industry: "Internet Content & Information",
    country: "United States",
    sharesOutstanding: "12.3B",
    description:
      "Alphabet Inc. is a holding company that gives ambitious projects the resources, freedom, and focus to make their ideas happen.",
    foundedYear: 1998,
    latestNews: [],
  },
  tD05: {
    tokenAddress: "0x2ba5a6aa9fd6cf52b30ccb2fddefd505b34f0eb9" as Address,
    name: "Tokenized DBS Group Holdings",
    symbol: "tD05",
    price: "$35.00",
    lastUpdated: new Date(),
    assetType: "STOCK",
    assetIcon: "https://companieslogo.com/img/orig/D05.SI-edfcd000.png?t=1720244491",
    companyName: "DBS Group Holdings Ltd",
    marketCap: "$94B",
    website: "https://www.dbs.com",
    industry: "Banking",
    country: "Singapore",
    sharesOutstanding: "2.7B",
    description:
      "DBS Group Holdings Ltd is a Singaporean multinational banking and financial services corporation.",
    foundedYear: 1968,
    latestNews: [],
  },
  tBREN: {
    tokenAddress: "0x751d67bcbfa63acc27e6a6514fbeb27365d3dd38" as Address,
    name: "Tokenized Barito Renewables",
    symbol: "tBREN",
    price: "$0.00",
    lastUpdated: new Date(),
    assetType: "STOCK",
    assetIcon: "https://www.barito-pacific.com/fe/assets/icons/favicon_barito1.png",
    companyName: "Barito Renewables Energy",
    marketCap: "$2.5B",
    website: "https://www.bren.co.id",
    industry: "Renewable Energy",
    country: "Indonesia",
    sharesOutstanding: "5.0B",
    description:
      "Barito Renewables Energy is an Indonesian renewable energy company focused on developing sustainable energy solutions.",
    foundedYear: 2012,
    latestNews: [],
  },
  tDELTA: {
    tokenAddress: "0x616a76c281f2f805499ae46a6c7c3a6a3a62cdc0" as Address,
    name: "Tokenized Delta Electronics",
    symbol: "tDELTA",
    price: "$175.00",
    lastUpdated: new Date(),
    assetType: "STOCK",
    assetIcon: "https://www.deltathailand.com/imgadmins/news/news_cover/DELTA_news_photo2019-02-27_15-17-12.jpg",
    companyName: "Delta Electronics Thailand PCL",
    marketCap: "$65B",
    website: "https://www.deltaww.com",
    industry: "Electronics Manufacturing",
    country: "Taiwan",
    sharesOutstanding: "2.6B",
    description:
      "Delta Electronics Inc. specializes in power and thermal management solutions, automation, and infrastructure.",
    foundedYear: 1971,
    latestNews: [],
  },
  tMAYBANK: {
    tokenAddress: "0x04d1edf5252c35d3c1f7e6a5f934b6ab12f66220" as Address,
    name: "Tokenized Maybank",
    symbol: "tMAYBANK",
    price: "$10.00",
    lastUpdated: new Date(),
    assetType: "STOCK",
    assetIcon: "https://w7.pngwing.com/pngs/280/197/png-transparent-maybank-finance-money-permodalan-nasional-berhad-interior-design-logo-saving-food-text.png",
    companyName: "Maybank",
    marketCap: "$76B",
    website: "https://www.maybank.com",
    industry: "Banking",
    country: "Malaysia",
    sharesOutstanding: "10.9B",
    description:
      "Malayan Banking Berhad is a Malaysian universal bank, with the largest market capitalisation on Bursa Malaysia.",
    foundedYear: 1960,
    latestNews: [],
  },
  tXAU: {
    tokenAddress: "0xf80567a323c99c99086d0d6884d7b03aff5c8903" as Address,
    name: "Tokenized Gold",
    symbol: "tXAU",
    price: "$2650.00",
    lastUpdated: new Date(),
    assetType: "COMMODITY",
    assetIcon: "https://cdn-icons-png.flaticon.com/512/2583/2583963.png",
    companyName: "Gold",
    marketCap: "$13T",
    website: "https://www.gold.org",
    industry: "Precious Metals",
    country: "Global",
    sharesOutstanding: "197,576 tonnes",
    description:
      "Gold is a precious metal that has been used as a store of value and medium of exchange for thousands of years.",
    foundedYear: 0,
    latestNews: [],
  },
  tXAG: {
    tokenAddress: "0xa2f75a99ea1133f72673ddbbbe01a0080e5c6e52" as Address,
    name: "Tokenized Silver",
    symbol: "tXAG",
    price: "$31.00",
    lastUpdated: new Date(),
    assetType: "COMMODITY",
    assetIcon: "https://cdn-icons-png.flaticon.com/512/2583/2583967.png",
    companyName: "Silver",
    marketCap: "$1.6T",
    website: "https://www.silverinstitute.org",
    industry: "Precious Metals",
    country: "Global",
    sharesOutstanding: "1.74B oz",
    description:
      "Silver is a precious metal widely used in jewelry, electronics, and industrial applications. It's also considered an investment vehicle.",
    foundedYear: 0,
    latestNews: [],
  },
  tBTC: {
    tokenAddress: "0x8049cd4055b32e810efad90e998bbe82a58d5ab9" as Address,
    name: "Tokenized Bitcoin",
    symbol: "tBTC",
    price: "$100000.00",
    lastUpdated: new Date(),
    assetType: "CRYPTO",
    assetIcon: "https://cdn-icons-png.flaticon.com/512/5968/5968260.png",
    companyName: "Bitcoin",
    marketCap: "$1.9T",
    website: "https://bitcoin.org",
    industry: "Cryptocurrency",
    country: "Global",
    sharesOutstanding: "19.7M BTC",
    description:
      "Bitcoin is a decentralized digital currency that can be transferred on the peer-to-peer bitcoin network without the need for intermediaries.",
    foundedYear: 2009,
    latestNews: [],
  },
  tTSLA: {
    tokenAddress: "0x0000000000000000000000000000000000000000" as Address,
    name: "Tokenized Tesla Stock",
    symbol: "tTSLA",
    price: "$250.00",
    lastUpdated: new Date(),
    assetType: "STOCK",
    assetIcon: "https://logo.clearbit.com/tesla.com",
    companyName: "Tesla, Inc.",
    marketCap: "$800B",
    website: "https://www.tesla.com",
    industry: "Electric Vehicles",
    country: "United States",
    sharesOutstanding: "3.2B",
    description:
      "Tesla, Inc. is an American electric vehicle and clean energy company based in Austin, Texas. Tesla designs and manufactures electric vehicles, energy storage systems, and solar panels.",
    foundedYear: 2003,
    latestNews: [],
  },
  tETH: {
    tokenAddress: "0x0000000000000000000000000000000000000000" as Address,
    name: "Tokenized Ethereum",
    symbol: "tETH",
    price: "$3500.00",
    lastUpdated: new Date(),
    assetType: "CRYPTO",
    assetIcon: "https://cdn-icons-png.flaticon.com/512/14446/14446160.png",
    companyName: "Ethereum",
    marketCap: "$420B",
    website: "https://ethereum.org",
    industry: "Cryptocurrency",
    country: "Global",
    sharesOutstanding: "120.3M ETH",
    description:
      "Ethereum is a decentralized platform that runs smart contracts and serves as the foundation for decentralized applications and the broader DeFi ecosystem.",
    foundedYear: 2015,
    latestNews: [],
  },
};

export const NEWS_KEYWORDS: Record<string, string> = {
  tAAPL: "Apple stock AAPL",
  tNVDA: "NVIDIA stock NVDA",
  tMSFT: "Microsoft stock MSFT",
  tGOOG: "Google Alphabet stock GOOGL",
  tD05: "DBS Group Holdings bank Singapore",
  tBREN: "Barito Renewables Energy Indonesia",
  tDELTA: "Delta Electronics Taiwan",
  tMAYBANK: "Maybank Malaysia banking",
  tXAU: "Gold precious metal commodity",
  tXAG: "Silver precious metal commodity",
  tBTC: "Bitcoin cryptocurrency BTC",
  tTSLA: "Tesla stock TSLA electric vehicle",
  tETH: "Ethereum cryptocurrency ETH",
};

export const NEWS_CONFIG = {
  // Using NewsAPI.org (free tier available)
  NEWS_API_BASE_URL: "https://newsapi.org/v2/everything",
  NEWS_API_KEY: "", // Add this to your .env file as NEXT_PUBLIC_NEWS_API_KEY

  // Alternative: Alpha Vantage News API
  ALPHA_VANTAGE_BASE_URL: "https://www.alphavantage.co/query",
  ALPHA_VANTAGE_API_KEY: "", // Add this to your .env file as NEXT_PUBLIC_ALPHA_VANTAGE_API_KEY

  // Default news settings
  DEFAULT_PAGE_SIZE: 5,
  DEFAULT_SORT_BY: "publishedAt",
  DEFAULT_LANGUAGE: "en",
};
